server:
    port: 8080
spring:
    application:
        name: redis
    redis:
        database: 10
        host: 192.168.2.250
        port: 6380
        ssl: false
        timeout: 10000 # Connection timeout.